const authRouter = require('./authRoutes')
const userRoutes = require('./userRoutes')
const offerRoutes = require("./offerRoutes")
const serviceRouter = require("./serviceRoutes")
const plogRouter = require("./plogRout")
const petRouter = require("./petRoutes")
const communityRouter = require("./communityRoutes")
const vetRouter = require("./vetRoutes")
const doctorRouter = require("./doctorsRouts")
const productRouter = require("./productRoutes")
const shelterRouter = require("./shelterRoutes")
const requestRouter = require('./requestRoutes')
const AIRouter = require('./AIRoutes')
const reviewRouter = require("./reviewRouts")
const foundedRouters = require('./foundedRoutes')
const favRoutes = require("./favListRoutes")
const couponRoutes = require("./couponRoutes")
const cartRoutes = require("./cartRoutes")
const serviceProfileRoutes = require("./serviceProfileRoutes")
const vaccineRoutes = require('./vaccineRoutes')
const reminderRoutes = require('./reminderRoutes')
const orderRoutes = require("./orderRoutes")

const mountRoutes = (app) => {
    app.use('/scooby/api/users', authRouter)
    app.use('/scooby/api/user', userRoutes)
    app.use("/scooby/api/offer", offerRoutes)
    app.use('/scooby/api/services', serviceRouter)
    app.use('/scooby/api/Plogs', plogRouter)
    app.use('/scooby/api/Pets', petRouter)
    app.use('/scooby/api/community', communityRouter)
    app.use('/scooby/api/vet', vetRouter)
    app.use('/scooby/api/doctors', doctorRouter)
    app.use('/scooby/api/product', productRouter)
    app.use('/scooby/api/shelters', shelterRouter)
    app.use('/scooby/api/AI', AIRouter)
    app.use('/scooby/api/request', requestRouter)
    app.use('/scooby/api/reviews', reviewRouter)
    app.use('/scooby/api/founded', foundedRouters)
    app.use('/scooby/api/fav', favRoutes)
    app.use('/scooby/api/coupon', couponRoutes)
    app.use('/scooby/api/cart', cartRoutes)
    app.use('/scooby/api/serviceProfile', serviceProfileRoutes)
    app.use('/scooby/api/vaccine', vaccineRoutes)
    app.use('/scooby/api/reminder', reminderRoutes)
    app.use('/scooby/api/order', orderRoutes)
}
module.exports = mountRoutes; 